### PR TITLE
Mobile filter parity

### PR DESCRIPTION
**Pull request by jlhogan**
## Changes

- In mobile, filters are now applied on selection (as opposed to after "apply" button click)
- "Filter results" button becomes "View ## results" button, which sticks to bottom of screen/bottom of filter drawer
- When filters are applied, "clear all filters" button lives underneath "view results" button in bottom button bar

Thoughts: 
- the changing count in button text is not super noticeable IMO; @admoorgit thoughts for how to make it pop more? Bigger font?
- Should clicking "clear all filters" close filter drawer ? 

## Screenshots

mobile_filters

## Checklist

- ~[ ] if adds a new page, adds accessibility tests~
- ~[ ] if adds a new page or new interaction, adds e2e test~
- [ ] if adds a new page or new interaction, sends google analytics events and updates [GA doc](https://docs.google.com/document/d/1DfQDUNZPO3B352EhUwXp0el6qrAWz8Jq9cTa1yv8Ty4/edit) <-- this should just work and match events from desktop interactions now (please confirm, @cathydeng !) EDIT: update GA doc to note "apply filter" event is deprecated
- ~[ ] if changes filter functionality, updates [filters doc](https://docs.google.com/document/d/1yEdo7IpHCtEKNNF6FMLapBUgcPw_8CY7wGwxKTdtJrU/edit)~

Fixes https://app.asana.com/0/1202690670605811/1203031893746133/f

### CODE REVIEW

**Review by cathydeng — APPROVED** [review]
- i actually think the result count button feels pretty clean/intuitive! imo it is clear that toggling checkboxes/radios changes the result set. also slight bias against introducing more button styles, but defer to adam on thoughts for tweaking the visual design here
- it miiight make more sense to close the drawer upon clearing filters? but don't feel strongly - it's entirely possible that people would use the clear filters button as a starting point to adjusting filters, rather than to immediately view results
- confirming that analytics events are still good and don't need any updates - we'd just wanna update the doc to note that the apply filters event is deprecated
- heads up that i just merged the search page tests and you may need to tweak the mobile tests after rebase 🙈

**Review by admoorgit — COMMENTED** [review]
OOOOOO HOW FANCY!
• I think once people see the number in the button it'll click. And also if you have no filters selected, there's a nice transition from stroked button to filled button which is real nice
• Agree we can bump up the font size in the button — let's go with 1.25
• And let's make the button itself a lil taller. padding: 1rem 1.25rem;
• I vote against closing the menu on clear — they may ONLY want to clear, not clear and close
  - We could make a sticky ( X ) in the upper right corner if we're concerned about their ability to close easily, OR
  - We can move clear ABOVE the button, and add a "Close filters" underneath — though I worry that'll get a little bih zee
• Can we add a 1px stroke above the button to separate it a lil more from the filters themselves?

**Comment by admoorgit** [comment]
@jlhogan getting closer! Here are some thoughts:

- Now that I'm futzing with it, I think the "Close" button should actually be "Cancel" to suggest it won't apply the filters, since it doesn't
- Please change "Filtered by" to "Filter by" to make it more actionable
   - We should also make this text smaller so it fits on one line — H2 mobile size, and make all the filter titles H3 sizes
- Page still scrolls past the "View/Clear" buttons but is only the footer, which is progress! Possible to not see the footer on scroll?
- Page should pop to the top if clicking View OR Cancel (so people don't get confused about where they are)

I think that's it! If you have any questions I'm around.
- a.

**Comment by admoorgit** [comment]
@jlhogan this is great! Only change is to get "Filter by..." on 1 line. Otherwise approved!

**Pull request merged**
