### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by jlhogan**
## Changes

updates data icons to have background; updates icons in other contexts to be styled appropriately

fixes https://app.asana.com/0/1202105544020589/1204082512322688/f

### CODE REVIEW

**Review by SMakaiTakori — APPROVED** [review]
LGTM!

**Review by alex-cds — CHANGES_REQUESTED** [review]
@SMakaiTakori @jlhogan Fancy new icons! Thank you! Few notes
1. At bottom of provider detail page, the blue section telling providers how to update their info has an icon. It used to be white and now it's some sort of blue that's blending into the blue background color of the section. 
Option are: 
A. Bring back the white book icon for this area. 
B. Just remove the icon altogether from this section.
image
(Shown in screenshot is the blueish icon on the blue background) 

2. The PRINT and SHARE text links and icons are slightly diff color right now. Possible to make them same color and/or standardize text link + icon styling? (If this is too out of scope, ignore!)

**Comment by alex-cds** [comment]
Fabulous! LGTM! @jlhogan

**Review by alex-cds — APPROVED** [review]
Thank you!!

**Pull request merged**
