### PR TITLE
First pass at triggering modal on specific event threshold

### PR DESCRIPTION
**Pull request by jlhogan**
FULL PR DESCRIPTION TO COME, just getting this up to get eyes on it ASAP because we want this rolled out this week. 

todo: 
- content and styles for modal! 

## Screenshots

[Add screenshots or GIFs here]

## Checklist

- [ ] if changes filter/search functionality, adds or updates unit tests
- [ ] if adds a new page, adds accessibility tests
- [ ] if adds a new page or new interaction, adds e2e test
- [ ] if adds a new page or new interaction, sends google analytics events and updates [GA doc](https://docs.google.com/document/d/1DfQDUNZPO3B352EhUwXp0el6qrAWz8Jq9cTa1yv8Ty4/edit)
- [ ] if changes filter functionality, updates [filters doc](https://docs.google.com/document/d/1yEdo7IpHCtEKNNF6FMLapBUgcPw_8CY7wGwxKTdtJrU/edit)

Fixes [link to asana ticket here]

### CODE REVIEW

**Review by admoorgit — COMMENTED** [review]
@jlhogan 
Def works when clicking filters, but it feels like an error state to me, since it happens on a click where I'm expecting something to happen. Would feel more natural when navigating between pages. We can chat about this at stand-up.

Also can we make it pop less abruptly? That may be part of what felt so invasive — it's like OH YOU CLICKED A BUTTON?! POW ANSWER QUESTIONS NOW!

We may need to tweak design so it's not a full takeover. When I designed it I was assuming it'd be on exit, not during the experience, so we may want to adjust where it pops and what that looks like.

**Comment by SMakaiTakori** [comment]
> @jlhogan Def works when clicking filters, but it feels like an error state to me, since it happens on a click where I'm expecting something to happen. Would feel more natural when navigating between pages. We can chat about this at stand-up.
> 
> Also can we make it pop less abruptly? That may be part of what felt so invasive — it's like OH YOU CLICKED A BUTTON?! POW ANSWER QUESTIONS NOW!
> 
> We may need to tweak design so it's not a full takeover. When I designed it I was assuming it'd be on exit, not during the experience, so we may want to adjust where it pops and what that looks like.

@jlhogan @admoorgit 
Standup Notes:

@vkidd-bloom and I tested the modal events through this deployment. Vicki is wondering if we can have the modal pop up in the corner of the user's screen, so that their experience isn't disrupted by the modal overtaking the screen and disabling the actions behind it.  

I am thinking, we may need to switch to using a toast-notification instead of a modal to display the exit survey prompt. The user experience won't be interrupted because the alert will just pop in the corner and stay there until the user clicks for it to close. If the modal can do this that would be great but I have only worked with modals that overtake the user's other actions.

**Comment by admoorgit** [comment]
> 

@SMakaiTakori @vkidd-bloom agree with making it less invasive by tucking it down on the page. With that approach, it can be persistent but not diminish any functionality. I dig. @jlhogan if this is possible, could you provide me with some parameters (location, size, etc) so I can tweak the design?

@vkidd-bloom we should run this by Karyn today to show her the issue + explain how invasive in is in it's current form and implementation (e.g.; popping after an action as opposed to fully leaving the site). Seeing in action may be more impactful than simply talking about it.

**Review by SMakaiTakori — COMMENTED** [review]
Everything looks great to me codewise @jlhogan , your naming conventions are perfect and the folks at the BHA standup today are happy with the progress on this 🥳 .

I know @admoorgit has a few design tweaks to the modal but after those are in, we will be set to merge this in!

**Comment by SMakaiTakori** [comment]
@jlhogan looks like your tests are failing due to something with translations maybe? After this is fixed, we plan to merge this in.

**Review by SMakaiTakori — APPROVED** [review]
This all looks great to me!

**Pull request merged**
