### PR TITLE
Add back button to guided search

### PR DESCRIPTION
**Pull request by jlhogan**
guided_search_back_button

### CODE REVIEW

**Review by amdarnell7 — APPROVED** [review]
This looks great. I love how it retains the answer even when going back and forth.

**Review by admoorgit — CHANGES_REQUESTED** [review]
Nice. Small changes and we're good to go 
image

**Comment by admoorgit** [comment]
Please note you may want to make a new class — I edited .usa-button directly to see changes

**Review by admoorgit — APPROVED** [review]
Link works as expected in desktop and mobile, and across all questions. Especially like how selections are retained even if not submitted! Approved.

**Review by ElvisJG — APPROVED** [review]

**Pull request merged**
