### PR TITLE
Compare cleanup

### PR DESCRIPTION
**Pull request by jlhogan**
## Changes

- Adds messaging to hours table if no info
- hides services tables if both providers do not have any mental health or substance use services
- resets compare selections when navigating back to search results 

Fixes https://app.asana.com/0/1202690670605811/1203315757494874/f

### CODE REVIEW

**Review by SMakaiTakori — APPROVED** [review]
LGTM!

**Review by admoorgit — CHANGES_REQUESTED** [review]
One change: on mobile let's make the data headings (monday, self pay, available) 400 weight so they match desktop. Seeing the non-bold days of the week is fine on both.

**Comment by jlhogan** [comment]
@admoorgit done !

**Review by admoorgit — APPROVED** [review]
looks good!

**Pull request merged**
