### PR TITLE
add complaint section to detail page

### PR DESCRIPTION
**Pull request by cathydeng**
adding a complaint section to the detail page, and also made a HighlightBox component to share some styling w/ the alert at the top of the page

Screen Shot 2022-08-17 at 3 08 02 PM

one concern that i wanna double-check w/ @admoorgit @amdarnell7: this now takes up a lot of real estate, and is now the most visually prominent thing on a provider's detail page, even tho it should (hopefully) be infrequently used functionality. are we ok with this & how it may come off to providers? would we want to visually de-emphasize this a bit (e.g. by relying on the contact-us link for phone/email/deets and shortening to just 1-2 sentences, or making this a section that expands upon click)?

also this is pending spanish translations - i just manually updated the english translation json for now to confirm that the react-i18next interpolation was working properly

### CODE REVIEW

**Comment by jlhogan** [comment]
agreed that making this collapsed by default and expandable on click would make more sense to me.
Also, I made you an editor on the google sheet (sorry!) so you can add the content to the sheet without the spanish translations for now. 

Additionally, I think the use of the tag index in the content for the Trans component is brittle and likely confusing for folks who are not interacting with the implementation in the app... might it be more easily understandable if we just partition the content into chunks with explainers like complaintFormInfoBeforeLink/complaintFormLink/complaintFormInfoAfterLink ... it's definitely chunkier but i think will read more clearly in the content sheet to ppl without the technical context

**Comment by amdarnell7** [comment]
@admoorgit @cathydeng I agree this is a bit too prominent on the page. I know that the licensing and designation team want to maintain a level of standardization around the methods for communicating complaint channels so I think the ideal approach may be the collapsed detail.

**Comment by cathydeng** [comment]
@jlhogan gonna keep the trans b/c there are plans to add a bunch more languages, and that increases the likelihood that words will be in different orders grammatically and the chunks may not be the same. i'll keep an eye on the translated copy to make sure the tags are in there - hopefully we'll only have a small handful of strings like this

**Comment by cathydeng** [comment]
@admoorgit @amdarnell7 updated to use an accordion that's collapsed by default, and also updated the title to be more of a prompt for opening the accordion. tried to make it match the language on the [bha contact page](https://bha.colorado.gov/contact/contact-us) - lmk if this updated ui works / if you have any feedback

https://user-images.githubusercontent.com/1406537/185503989-ecf341c2-3610-4233-9e50-c2c6922788a6.mov

**Comment by admoorgit** [comment]
Love it! Let's make sure we use the same styling accordion here as we do on the FAQ. May want to coordinate with Julia on that. Figma styling is here for reference: [https://www.figma.com/file/FYAW3dTCEgGsCQ2V4G54LQ/Care-Directory?node-id=969%3A2407](https://www.figma.com/file/FYAW3dTCEgGsCQ2V4G54LQ/Care-Directory?node-id=969%3A2407)

**Review by amdarnell7 — APPROVED** [review]

**Review by jlhogan — APPROVED** [review]
LGTM. My vote would be to use markdown as we discussed for in-line links in text blocks, but I can update this to match that when the FAQ stuff lands. If that happens first, would be good to update this PR to match IMO

**Review by admoorgit — APPROVED** [review]
Works as expected! May adjust styling (blue on active) but that can happen at a later date.

**Pull request merged**
