### PR TITLE
New hero image

### PR DESCRIPTION
**Pull request by jeffmaher**
Adds the new hero image to get it to the (below) design by @admoorgit. With that said, I don't have the mobile display quite to the spec (i.e. focused in on the "C"), but figure this might be good for now (i.e. good enough for hard launch tomorrow) OR perhaps @jlhogan or @ElvisJG can finish off before me.

Design spec:
image

### CODE REVIEW

**Review by amdarnell7 — APPROVED** [review]
I love it!

**Review by admoorgit — CHANGES_REQUESTED** [review]
Desktop looks great! What @ElvisJG is working on in chat looks great for mobile. Only set it to request changes so we can nail that.

**Comment by ElvisJG** [comment]
https://user-images.githubusercontent.com/44843903/180892532-250005a7-53d3-4262-93fd-96f28ee31089.mp4

**Review by jlhogan — APPROVED** [review]
LGTM ! 🚀

**Review by admoorgit — APPROVED** [review]
nice!

**Pull request merged**
