### PR TITLE
final changes before hard launch

### PR DESCRIPTION
**Pull request by jlhogan**
changes to footer:
- increased width 
- padding above BHA logo in mobile
- boldified "our commitment" header to match other headers on page

changes to header/banner:
- pulled out crisis hotline into a dismissible alert below the header that is present on every page (unless hidden by user)

changes to homepage content:
- adding padding to homepage title in mobile

changes to guided search:
- makes guided search forms wider on desktop
- reuses app alert component in guided search 
    - type of help input: content when user selects 'suicidal thoughts' option
    - distance input: data collection content
- fixes unselectable options in type of help
- moves type of help suicidal thoughts content directly under selection

changes to search results:
- padding on right (map) side of screen
- moves zoom control to top right of map
- adds suicidal ideation option as separate filter in search filters (pulled out of 'mental health' option)

changes to result detail:
- consistent header styling
- details / services are side by side columns (not stacked)

ALSO updates all content to match final content + translations in google doc

### CODE REVIEW

**Review by amdarnell7 — APPROVED** [review]

**Review by admoorgit — CHANGES_REQUESTED** [review]
**NEW**
General: 
- [x] Trebuchet MS seems larger than Museo — let’s bring H2 size down to 1.3rem
- [ ] MOBILE: Own Path + CO breaks onto 2 lines on iPhone SE — have it shrink a little more on smaller screens please


changes to footer:
- [x] increased width
- [x] padding above BHA logo in mobile
- [x] boldified "our commitment" header to match other headers on page

- [ ] May want to move BHA logo above the text on mobile but let's discuss (doesn't have to be done for hard launch)


changes to header/banner:
- [x] pulled out crisis hotline into a dismissible alert below the header that is present on every page (unless hidden by user)

changes to homepage content:
- [x] adding padding to homepage title in mobile

**NEW**
- [x] Mobile — Crisis hotline phone number needs to be on 1 line
- [x] Needs new guided search content (see Figma)
- [x] Mobile — shrink padding around zip code content so it fits on 2 lines on most phones (.75rem)
- [x] Standup: hyperlink “Call #” only
- [x] Content updates (see Figma) for CCS and imatter links

changes to guided search:
- [x] makes guided search forms wider on desktop
- [x] reuses app alert component in guided search
- [x] type of help input: content when user selects 'suicidal thoughts' option
- [x] distance input: data collection content
- [x] fixes unselectable options in type of help
- [x] moves type of help suicidal thoughts content directly under selection

**NEW**
- [x] Change H1 (question 1 of 6) font-size to 1.125rem;
- [x] Shrink Zip Code field width so it’s more representative of the data that’ll populate it
- [x] MOBILE BUG — clicking “guided experience” on homepage scrolled me to the bottom of the first question page
- [x] Add 1rem padding below question content
- [x] Add 1rem padding above button (or below selections, whichever)
- [x] Remove main crisis notification during this sequence
- [x] MOBILE — Shrink top margin above “Question 1 of 6” to 1 rem
- [x] MOBILE — Remove top margin above the actual question

changes to search results:
- [x] padding on right (map) side of screen
- [x] moves zoom control to top right of map
- [x] adds suicidal ideation option as separate filter in search filters (pulled out of 'mental health' option)

**NEW**
- [ ] MOBILE: Consider adding “Apply” button under each filter section, with Apply Filters remaining at the bottom
- [ ] MOBILE: Map on safari mobile broken — zoomed way out, only 1 pin. Map off-center

changes to result detail:
- [ ] consistent header styling
- [x] details / services are side by side columns (not stacked)

**NEW**
- [x] Facility title should be H1 @ 2rem
- [x] Details / Services should be H2 @ 1.5rem
- [x] Pop served/access can be <P> Bold maybe? Or alternate/smaller H3 (make same change on Result page) ... let's discuss
- [x] Pop served/access bulleted lists instead of comma separated to match the rest of the data

**Comment by jeffmaher** [comment]
@jlhogan : Ping me when you need a review. Otherwise, I'll pop in 8-9:30a ET tomorrow at the latest to review, or if I wind up having time later this evening.

**Comment by admoorgit** [comment]
Looks good to me!

**Comment by amdarnell7** [comment]
I am sure this is just my machine or already identified but I wanted to flag just in case. The search bar is condensed
Screen Shot 2022-07-25 at 7 53 05 PM

**Comment by admoorgit** [comment]
@amdarnell7 we shrunk the field universally to be more representative of the length of the required entry — in this case, a zip code. That said, if it seems too small we can maybe double it in length without too much lift, yeah @jlhogan @ElvisJG ?

**Comment by amdarnell7** [comment]
Okay, yeah if we could that would be awesome for launch. It looks a little funky on mobile too but I totally understand the thought for sure.
IMG_1224

**Review by admoorgit — APPROVED** [review]
Zip code fix looks good

**Review by jeffmaher — APPROVED** [review]
LGTM

**Pull request merged**
