### PR TITLE
Age filter

### PR DESCRIPTION
**Pull request by jlhogan**
Visible changes: 
- Adds age group filter to tool, on search page and in guided search
- For direct zip code search, age group is not set. For zipcode search, user does not see age group filter in active state until they select a different value from the dropdown. 
- Currently, user cannot unselect an age group once they have picked one (Should we add an option for "any"?)
- Adds differentiated language to guided search based on answer to question (who are you looking for help for?)

Code changes:
- decomposed giant `types.ts` and `utils.ts` files because they were unwieldy and added MORE to them was confusing and overwhelming.
    -  Now, `types` is a directory containing `care_provider.ts` which has the CareProvider type and all associated data types; and `search.ts` which contains all additional types required for searching (CareProviderSearchResult, SearchResult, ZipData, ZipMeta, and enum types used for special composed search filters that don't directly map to CareProvider data values)
    - `utils` is a directory containing `search.ts` which has helper functions related to searching, and a sub-directory `filters` which contains a file for each type of search filter, with the logic for applying that filter to a set of CareProvider data

### CODE REVIEW

**Review by admoorgit — APPROVED** [review]
Looks good to me! Functions in desktop and mobile as expected. 

**Answers to questions:** 
For direct zip code search, age group is not set. For zipcode search, user does not see age group filter in active state until they select a different value from the dropdown.  **— This sounds right to me.**
Currently, user cannot unselect an age group once they have picked one (Should we add an option for "any"?) **— All, maybe? That suggests that they're all included a tad more imo**
Adds differentiated language to guided search based on answer to question (who are you looking for help for?) **— Differentiated language is great! Yay!**

**Comment by admoorgit** [comment]
@jlhogan  Re: Any/All. I don't think we need to add that functionality now, so I'd maybe table it for other more pressing updates — especially since it'd likely require more input from CO folk. Also not sure anyone wouldn't know which age group they'd fall in or the person they care for would. But we can track and see if it becomes an issue.

**Review by amdarnell7 — APPROVED** [review]
This is great, thank you. As for the 'any' option, I would say let's plan to test it but for now this is perfect.

**Review by jeffmaher — APPROVED** [review]
LGTM

**Pull request merged**
