### PR TITLE
Adds button to increase distance when no results

### PR DESCRIPTION
**Pull request by jlhogan**
Also:
- fixes flag controlling when age filter is displayed as active
- ensures distance filter displayed as active when distance is updated
by expand search radius button
- removes extra state variable tracking search params so that search
results are updated when using browser back button

### CODE REVIEW

**Review by amdarnell7 — CHANGES_REQUESTED** [review]
Annoying change ask but can we remove the period on the button. Other than that it looks great

**Comment by jlhogan** [comment]
@amdarnell7 -- period removed! please re-review

**Review by admoorgit — APPROVED** [review]
Looks good to me! Does what expect in desktop and mobile. May address "distance" read out in the future, but will test to see if it's an issue.

**Review by ElvisJG — APPROVED** [review]

**Review by amdarnell7 — APPROVED** [review]
Thank you @jlhogan. This looks great.

**Pull request merged**
